name: build all

on:
  schedule:
    - cron: "0 2 */3 * *"
  pull_request:
  workflow_dispatch:

permissions:
  pull-requests: read

jobs:
  gen-matrix:
    runs-on: ubuntu-24.04
    outputs:
      kernelmatrix: ${{ steps.set-matrix-kernel.outputs.matrix }}
      ubootmatrix: ${{ steps.set-matrix-uboot.outputs.matrix }}
    steps:
      - uses: actions/checkout@v4
      - id: set-matrix-kernel
        run: |
          export matrix=$(ls kernel/profiles | jq -R -s -c 'split("\n")[:-1]')
          echo "::set-output name=matrix::$matrix"
      - id: set-matrix-uboot
        run: |
          export matrix=$(ls uboot/profiles | jq -R -s -c 'split("\n")[:-1]')
          echo "::set-output name=matrix::$matrix"

  build-kernel:
    needs: gen-matrix
    strategy:
      fail-fast: false
      matrix: 
        profile: ${{fromJson(needs.gen-matrix.outputs.kernelmatrix)}}
    uses: ./.github/workflows/build_kernel.yml
    secrets:
      GIT_TOKEN: ${{ secrets.GIT_TOKEN }}
    with:
      profile: ${{ matrix.profile }}

  build-uboot:
    needs: gen-matrix
    strategy:
      fail-fast: false
      matrix: 
        profile: ${{fromJson(needs.gen-matrix.outputs.ubootmatrix)}}
    uses: ./.github/workflows/build_uboot.yml
    secrets:
      GIT_TOKEN: ${{ secrets.GIT_TOKEN }}
    with:
      profile: ${{ matrix.profile }}

  upload-uboot-release:
    runs-on: ubuntu-24.04
    needs: build-uboot
    if: ${{ (success() || failure()) && github.event_name != 'pull_request' }}
    steps:
      - uses: actions/download-artifact@v4
        with:
          path: artifacts
          pattern: uboot-*
      - run: mkdir -p artifacts-upload
      - run: for artifact in $(ls artifacts); do mkdir -p artifacts-upload/$artifact; done
      - run: for artifact in $(ls artifacts); do tar czf artifacts-upload/$artifact/$artifact-$(date "+%Y%m%d").tar.gz -C artifacts/$artifact .; done
      - run: sudo apt -y install s3cmd
      - run: |
          echo "[default]" >> .s3-cf.conf
          echo "access_key = ${{ secrets.CF_S3_ACCESS_KEY }}" >> .s3-cf.conf
          echo "secret_key = ${{ secrets.CF_S3_SECRET_KEY }}" >> .s3-cf.conf
          echo "host_base = ${{ secrets.CF_S3_HOST }}" >> .s3-cf.conf
          echo "host_bucket = ${{ secrets.CF_S3_HOST_BUCKET }}" >> .s3-cf.conf
          echo "bucket_location = auto" >> .s3-cf.conf
          echo "enable_multipart = False" >> .s3-cf.conf
      - run: s3cmd --recursive -c ./.s3-cf.conf put artifacts-upload/* s3://deepin-ports-kernel/
